/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.89421
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.infusionsoft.model.InfusionsoftOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InfusionsoftTransaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-28T18:08:25.347Z")
public class InfusionsoftTransaction {
  @SerializedName("amount")
  private Double amount = null;

  @SerializedName("collection_method")
  private String collectionMethod = null;

  @SerializedName("contact_id")
  private Long contactId = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("errors")
  private String errors = null;

  @SerializedName("gateway")
  private String gateway = null;

  @SerializedName("gateway_account_name")
  private String gatewayAccountName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("order_ids")
  private String orderIds = null;

  @SerializedName("orders")
  private List<InfusionsoftOrder> orders = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("test")
  private Boolean test = null;

  @SerializedName("transaction_date")
  private String transactionDate = null;

  @SerializedName("type")
  private String type = null;

  public InfusionsoftTransaction amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public InfusionsoftTransaction collectionMethod(String collectionMethod) {
    this.collectionMethod = collectionMethod;
    return this;
  }

   /**
   * Get collectionMethod
   * @return collectionMethod
  **/
  @ApiModelProperty(value = "")
  public String getCollectionMethod() {
    return collectionMethod;
  }

  public void setCollectionMethod(String collectionMethod) {
    this.collectionMethod = collectionMethod;
  }

  public InfusionsoftTransaction contactId(Long contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Get contactId
   * @return contactId
  **/
  @ApiModelProperty(value = "")
  public Long getContactId() {
    return contactId;
  }

  public void setContactId(Long contactId) {
    this.contactId = contactId;
  }

  public InfusionsoftTransaction currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public InfusionsoftTransaction errors(String errors) {
    this.errors = errors;
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public String getErrors() {
    return errors;
  }

  public void setErrors(String errors) {
    this.errors = errors;
  }

  public InfusionsoftTransaction gateway(String gateway) {
    this.gateway = gateway;
    return this;
  }

   /**
   * Get gateway
   * @return gateway
  **/
  @ApiModelProperty(value = "")
  public String getGateway() {
    return gateway;
  }

  public void setGateway(String gateway) {
    this.gateway = gateway;
  }

  public InfusionsoftTransaction gatewayAccountName(String gatewayAccountName) {
    this.gatewayAccountName = gatewayAccountName;
    return this;
  }

   /**
   * Get gatewayAccountName
   * @return gatewayAccountName
  **/
  @ApiModelProperty(value = "")
  public String getGatewayAccountName() {
    return gatewayAccountName;
  }

  public void setGatewayAccountName(String gatewayAccountName) {
    this.gatewayAccountName = gatewayAccountName;
  }

  public InfusionsoftTransaction id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public InfusionsoftTransaction orderIds(String orderIds) {
    this.orderIds = orderIds;
    return this;
  }

   /**
   * Get orderIds
   * @return orderIds
  **/
  @ApiModelProperty(value = "")
  public String getOrderIds() {
    return orderIds;
  }

  public void setOrderIds(String orderIds) {
    this.orderIds = orderIds;
  }

  public InfusionsoftTransaction orders(List<InfusionsoftOrder> orders) {
    this.orders = orders;
    return this;
  }

  public InfusionsoftTransaction addOrdersItem(InfusionsoftOrder ordersItem) {
    if (this.orders == null) {
      this.orders = new ArrayList<>();
    }
    this.orders.add(ordersItem);
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @ApiModelProperty(value = "")
  public List<InfusionsoftOrder> getOrders() {
    return orders;
  }

  public void setOrders(List<InfusionsoftOrder> orders) {
    this.orders = orders;
  }

  public InfusionsoftTransaction status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InfusionsoftTransaction test(Boolean test) {
    this.test = test;
    return this;
  }

   /**
   * Get test
   * @return test
  **/
  @ApiModelProperty(value = "")
  public Boolean isTest() {
    return test;
  }

  public void setTest(Boolean test) {
    this.test = test;
  }

  public InfusionsoftTransaction transactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Get transactionDate
   * @return transactionDate
  **/
  @ApiModelProperty(value = "")
  public String getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
  }

  public InfusionsoftTransaction type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfusionsoftTransaction transaction = (InfusionsoftTransaction) o;
    return Objects.equals(this.amount, transaction.amount) &&
        Objects.equals(this.collectionMethod, transaction.collectionMethod) &&
        Objects.equals(this.contactId, transaction.contactId) &&
        Objects.equals(this.currency, transaction.currency) &&
        Objects.equals(this.errors, transaction.errors) &&
        Objects.equals(this.gateway, transaction.gateway) &&
        Objects.equals(this.gatewayAccountName, transaction.gatewayAccountName) &&
        Objects.equals(this.id, transaction.id) &&
        Objects.equals(this.orderIds, transaction.orderIds) &&
        Objects.equals(this.orders, transaction.orders) &&
        Objects.equals(this.status, transaction.status) &&
        Objects.equals(this.test, transaction.test) &&
        Objects.equals(this.transactionDate, transaction.transactionDate) &&
        Objects.equals(this.type, transaction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, collectionMethod, contactId, currency, errors, gateway, gatewayAccountName, id, orderIds, orders, status, test, transactionDate, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfusionsoftTransaction {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    collectionMethod: ").append(toIndentedString(collectionMethod)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
    sb.append("    gatewayAccountName: ").append(toIndentedString(gatewayAccountName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderIds: ").append(toIndentedString(orderIds)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

