/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.infusionsoft.model.InfusionsoftEmailSentQueryResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InfusionsoftEmailSentQueryResultList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-16T20:40:42.950Z")
public class InfusionsoftEmailSentQueryResultList {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("emails")
  private List<InfusionsoftEmailSentQueryResult> emails = null;

  @SerializedName("next")
  private String next = null;

  @SerializedName("previous")
  private String previous = null;

  public InfusionsoftEmailSentQueryResultList count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public InfusionsoftEmailSentQueryResultList emails(List<InfusionsoftEmailSentQueryResult> emails) {
    this.emails = emails;
    return this;
  }

  public InfusionsoftEmailSentQueryResultList addEmailsItem(InfusionsoftEmailSentQueryResult emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<InfusionsoftEmailSentQueryResult>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * Get emails
   * @return emails
  **/
  @ApiModelProperty(value = "")
  public List<InfusionsoftEmailSentQueryResult> getEmails() {
    return emails;
  }

  public void setEmails(List<InfusionsoftEmailSentQueryResult> emails) {
    this.emails = emails;
  }

  public InfusionsoftEmailSentQueryResultList next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(value = "")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public InfusionsoftEmailSentQueryResultList previous(String previous) {
    this.previous = previous;
    return this;
  }

   /**
   * Get previous
   * @return previous
  **/
  @ApiModelProperty(value = "")
  public String getPrevious() {
    return previous;
  }

  public void setPrevious(String previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfusionsoftEmailSentQueryResultList emailSentQueryResultList = (InfusionsoftEmailSentQueryResultList) o;
    return Objects.equals(this.count, emailSentQueryResultList.count) &&
        Objects.equals(this.emails, emailSentQueryResultList.emails) &&
        Objects.equals(this.next, emailSentQueryResultList.next) &&
        Objects.equals(this.previous, emailSentQueryResultList.previous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, emails, next, previous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfusionsoftEmailSentQueryResultList {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

