/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * InfusionsoftProvincesByCode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-16T20:44:31.010Z")
public class InfusionsoftProvincesByCode {
  @SerializedName("provinces")
  private Map<String, String> provinces = new HashMap<String, String>();

  public InfusionsoftProvincesByCode provinces(Map<String, String> provinces) {
    this.provinces = provinces;
    return this;
  }

  public InfusionsoftProvincesByCode putProvincesItem(String key, String provincesItem) {
    this.provinces.put(key, provincesItem);
    return this;
  }

   /**
   * A key-value pair of province code and province name.
   * @return provinces
  **/
  @ApiModelProperty(required = true, value = "A key-value pair of province code and province name.")
  public Map<String, String> getProvinces() {
    return provinces;
  }

  public void setProvinces(Map<String, String> provinces) {
    this.provinces = provinces;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfusionsoftProvincesByCode provincesByCode = (InfusionsoftProvincesByCode) o;
    return Objects.equals(this.provinces, provincesByCode.provinces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provinces);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfusionsoftProvincesByCode {\n");
    
    sb.append("    provinces: ").append(toIndentedString(provinces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

