/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.infusionsoft.model.InfusionsoftCreateRestCustomFieldOption;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InfusionsoftCreateRestCustomField
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-16T20:40:42.950Z")
public class InfusionsoftCreateRestCustomField {
  /**
   * Gets or Sets fieldType
   */
  @JsonAdapter(FieldTypeEnum.Adapter.class)
  public enum FieldTypeEnum {
    CURRENCY("Currency"),
    
    DATE("Date"),
    
    DATETIME("DateTime"),
    
    DAYOFWEEK("DayOfWeek"),
    
    DRILLDOWN("Drilldown"),
    
    EMAIL("Email"),
    
    MONTH("Month"),
    
    LISTBOX("ListBox"),
    
    NAME("Name"),
    
    WHOLENUMBER("WholeNumber"),
    
    DECIMALNUMBER("DecimalNumber"),
    
    PERCENT("Percent"),
    
    PHONENUMBER("PhoneNumber"),
    
    RADIO("Radio"),
    
    DROPDOWN("Dropdown"),
    
    SOCIALSECURITYNUMBER("SocialSecurityNumber"),
    
    STATE("State"),
    
    TEXT("Text"),
    
    TEXTAREA("TextArea"),
    
    USER("User"),
    
    USERLISTBOX("UserListBox"),
    
    WEBSITE("Website"),
    
    YEAR("Year"),
    
    YESNO("YesNo");

    private String value;

    FieldTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FieldTypeEnum fromValue(String text) {
      for (FieldTypeEnum b : FieldTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FieldTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FieldTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FieldTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FieldTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("field_type")
  private FieldTypeEnum fieldType = null;

  @SerializedName("group_id")
  private Long groupId = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("options")
  private List<InfusionsoftCreateRestCustomFieldOption> options = null;

  @SerializedName("user_group_id")
  private Long userGroupId = null;

  public InfusionsoftCreateRestCustomField fieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
    return this;
  }

   /**
   * Get fieldType
   * @return fieldType
  **/
  @ApiModelProperty(required = true, value = "")
  public FieldTypeEnum getFieldType() {
    return fieldType;
  }

  public void setFieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
  }

  public InfusionsoftCreateRestCustomField groupId(Long groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * An optional tab group to place the field under in the interface.  If not specified, will default to the &#39;Custom Fields&#39; tab.
   * @return groupId
  **/
  @ApiModelProperty(value = "An optional tab group to place the field under in the interface.  If not specified, will default to the 'Custom Fields' tab.")
  public Long getGroupId() {
    return groupId;
  }

  public void setGroupId(Long groupId) {
    this.groupId = groupId;
  }

  public InfusionsoftCreateRestCustomField label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public InfusionsoftCreateRestCustomField options(List<InfusionsoftCreateRestCustomFieldOption> options) {
    this.options = options;
    return this;
  }

  public InfusionsoftCreateRestCustomField addOptionsItem(InfusionsoftCreateRestCustomFieldOption optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<InfusionsoftCreateRestCustomFieldOption>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @ApiModelProperty(value = "")
  public List<InfusionsoftCreateRestCustomFieldOption> getOptions() {
    return options;
  }

  public void setOptions(List<InfusionsoftCreateRestCustomFieldOption> options) {
    this.options = options;
  }

  public InfusionsoftCreateRestCustomField userGroupId(Long userGroupId) {
    this.userGroupId = userGroupId;
    return this;
  }

   /**
   * An optional user group to choose from when selecting values for User or UserListBox fields.
   * @return userGroupId
  **/
  @ApiModelProperty(value = "An optional user group to choose from when selecting values for User or UserListBox fields.")
  public Long getUserGroupId() {
    return userGroupId;
  }

  public void setUserGroupId(Long userGroupId) {
    this.userGroupId = userGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfusionsoftCreateRestCustomField createRestCustomField = (InfusionsoftCreateRestCustomField) o;
    return Objects.equals(this.fieldType, createRestCustomField.fieldType) &&
        Objects.equals(this.groupId, createRestCustomField.groupId) &&
        Objects.equals(this.label, createRestCustomField.label) &&
        Objects.equals(this.options, createRestCustomField.options) &&
        Objects.equals(this.userGroupId, createRestCustomField.userGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldType, groupId, label, options, userGroupId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfusionsoftCreateRestCustomField {\n");
    
    sb.append("    fieldType: ").append(toIndentedString(fieldType)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    userGroupId: ").append(toIndentedString(userGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

